const cartActionsTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    'ADD_ITEM': 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_CART_ITEM: 'CLEAR_CART_ITEM',
    ADD_QUANTITY: 'ADD_QUANTITY',
    CLEAR_QUANTITY: 'CLEAR_QUANTITY',
    ADD_ITEM_FROM_PRODUCT: 'ADD_ITEM_FROM_PRODUCT',
}

export default cartActionsTypes;